[package]
name = "xociety_nft"
edition = "2024.beta"

[dependencies]
# Sui framework
# For devnet: rev = "framework/devnet"
# For testnet: rev = "testnet"
# For mainnet: rev = "mainnet"
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet", override = true }

# Kiosk package for standard royalty_rule (TradePort compatible)
# For devnet: use local kiosk (published kiosk not available on devnet)
# For testnet/mainnet: use published kiosk (git)
# Kiosk = { local = "../../../kiosk-course/2-royalties/move/kiosk" }
Kiosk = { git = "https://github.com/MystenLabs/apps.git", subdir = "kiosk", rev = "testnet" }

# MultiSig package
multisig = { git = "https://github.com/MystenLabs/multisig-move.git", subdir = "move", rev = "main" }


[addresses]
xociety_nft = "0x0"

[dev-dependencies]

[dev-addresses]
